name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./CompanyEmployees/
    - name: Build
      run: dotnet build --no-restore ./CompanyEmployees/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./CompanyEmployees/
    - name: Publish
      run: dotnet publish ./CompanyEmployees/CompanyEmployees.csproj -c Release -o website
